In [1]:
import pandas as pd

#read player

player_crr_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/player_career_successes.csv')
player_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/players.csv')
player_ply_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/player_play.csv')
print('read players')

read players

In [2]:
# read games

games_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/games.csv')
print('read games')

read games

In [3]:
#read games 2023
game_trk_2023_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/game_tracking_2023.csv')
print('read games 2023')

read games 2023

In [4]:
#read games 2024
game_trk_2024_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/game_tracking_2024.csv')
print('read games 2024')

read games 2024

In [5]:
#read games 2025
game_trk_2025_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/game_tracking_2025.csv')
print('read games 2025')

read games 2025

In [6]:
#read combine
combine_trk_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/combine_tracking.csv')
combine_res_df = pd.read_csv('./nfl-big-data-bowl-2027/nfl-big-data-bowl-2027/combine_results.csv')
print("read combine")

read combine

In [37]:
#List of all current dfs
dfs = {'combine_res': combine_res_df, 'game_trk_2023': game_trk_2023_df, 'game_trk_2024': game_trk_2024_df, 
       'game_trk_2025': game_trk_2025_df, 'player_crr': player_crr_df, 'player': player_df, 
       'combine_trk': combine_trk_df, 'games': games_df, 'player_ply': player_ply_df}

player_df.head()

,nfl_id,draft_round,draft_pick_within_round,draft_overall_pick,nfl_position_C,nfl_position_CB,nfl_position_DB,nfl_position_DE,nfl_position_DT,nfl_position_FB,...,college_conference_Mountain West Conference,college_conference_Pacific Twelve Conference,college_conference_Patriot League,college_conference_Southeastern Conference,college_conference_Southern Conference,college_conference_Southland Conference,college_conference_Southwestern Athletic Conference,college_conference_Sun Belt Conference,college_conference_United Athletic Conference,Age
0,55867,1.0,3.0,3.0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,21
1,55870,1.0,6.0,6.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,21
2,55874,1.0,10.0,10.0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,21
3,55875,1.0,11.0,11.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,21
4,55877,1.0,13.0,13.0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,21

In [8]:

#==========================================================Begin Cleaning game_[year] ===============================================================
aggr_games_trk2025_df = dfs['game_trk_2025'].groupby(
    ['nfl_id']).agg(
    max_speed=('s','max'),
    avg_speed=('s', 'mean'),
    max_acceleration=('a','max'),
    avg_acceleration=('a','mean'),
    min_acceleration=('a','min'),
    total_frames=('s','count')
).reset_index()

In [9]:
aggr_games_trk2024_df = dfs['game_trk_2024'].groupby(
    ['nfl_id']).agg(
    max_speed=('s','max'),
    avg_speed=('s', 'mean'),
    max_acceleration=('a','max'),
    avg_acceleration=('a','mean'),
    min_acceleration=('a','min'),
    total_frames=('s','count')
).reset_index()

In [10]:
aggr_games_trk2023_df = dfs['game_trk_2023'].groupby(
    ['nfl_id']).agg(
    max_speed=('s','max'),
    avg_speed=('s', 'mean'),
    max_acceleration=('a','max'),
    avg_acceleration=('a','mean'),
    min_acceleration=('a','min'),
    total_frames=('s','count')
).reset_index()

In [27]:
all_aggr_games_trk_df = pd.concat([aggr_games_trk2023_df, aggr_games_trk2024_df], ignore_index = True)
all_aggr_games_trk_df = all_aggr_games_trk_df.groupby('nfl_id', as_index=False).agg(
    max_speed = ('max_speed', 'max'),
    avg_speed=('avg_speed', 'mean'),
    max_acceleration=('max_acceleration','max'),
    avg_acceleration=('avg_acceleration','mean'),
    min_acceleration=('min_acceleration','min'),
    total_frames=('total_frames','sum')
).reset_index()

all_aggr_games_trk_df = pd.concat([all_aggr_games_trk_df, aggr_games_trk2025_df], ignore_index = True)
all_aggr_games_trk_df = all_aggr_games_trk_df.groupby('nfl_id', as_index=False).agg(
    max_speed = ('max_speed', 'max'),
    avg_speed=('avg_speed', 'mean'),
    max_acceleration=('max_acceleration','max'),
    avg_acceleration=('avg_acceleration','mean'),
    min_acceleration=('min_acceleration','min'),
    total_frames=('total_frames','sum')
).reset_index()

# all_aggr_games_trk_df = all_aggr_games_trk_df.drop(columns = 'min_acceleration') #this column was always 0
#=============================================================================END cleaning game_[year]=================================================

,index,nfl_id,max_speed,avg_speed,max_acceleration,avg_acceleration,min_acceleration,total_frames
0,0,55867,9.17,2.462684,7.00,1.587976,0.0,153272
1,1,55870,8.29,1.610686,9.10,1.072430,0.0,208120
2,2,55874,8.26,1.799715,7.05,1.152037,0.0,255639
3,3,55875,7.62,1.736875,8.84,1.109342,0.0,225168
4,4,55877,9.52,2.549192,7.57,1.676818,0.0,93483

In [26]:

#====================================================================Begin clean combine_trk==========================================================
aggr_combine_trk_df = dfs['combine_trk'].loc[
    (dfs['combine_trk']['entity_type'] == 'PLAYER')].groupby(['nfl_id', 'drill_type']).agg(
    max_speed=('s', 'max'),
        avg_speed=('s', 'mean'),
        max_acceleration=('a', 'max'),
        avg_acceleration=('a', 'mean'),
        min_acceleration=('a', 'min'),
        total_frames=('s', 'count')
).reset_index()
aggr_combine_trk_df.loc[aggr_combine_trk_df['nfl_id'] == 55867]
#separate by drill
#====================================================================End clean combine_trk==========================================================

,nfl_id,drill_type,max_speed,avg_speed,max_acceleration,avg_acceleration,min_acceleration,total_frames
0,55867,FORTY_YARD_DASH,10.416667,7.966603,5.859557,1.921288,0.076739,52
1,55867,SKILL_DRILLS_LB,8.630000,4.453024,8.137175,2.873069,0.014907,797

In [13]:
# dfs['player_ply'].loc[(dfs['player_ply']['game_id'] == 2025111610) & (dfs['player_ply']['play_id'] == 2279)]
# '(8:42) (Shotgun) L.Jackson pass incomplete deep left to D.Hopkins.'
# print()
# dfs['player'].loc[dfs['player']['nfl_id'] == 57183] -> Roger Rosengarten

# player_play csv seems far too complicated for ml project

In [14]:
#======================================================================Begin encoding==========================================
aggr_combine_trk_df = pd.get_dummies(aggr_combine_trk_df, columns = ['drill_type'], dtype=int)

In [15]:
player_df = pd.get_dummies(player_df, columns = ['nfl_position', 'college_name', 'college_conference'], dtype=int)

In [16]:
player_df = player_df.drop(columns = 'display_name')

In [17]:
import numpy as np
player_df['Age'] = ((pd.to_datetime(player_df['draft_year'], format='%Y') - pd.to_datetime(player_df['birth_date'])).dt.days / 365.25).astype(int)

In [18]:
player_df = player_df.drop(columns = ['draft_year', 'birth_date'])

In [19]:
combine_res_df = pd.get_dummies(combine_res_df, columns = ['combine_position'], dtype=int)
#===============================================================end encoding =========================================================================

In [20]:

#====================================================Begin Standardizing ===============================
from sklearn.preprocessing import StandardScaler

encoded_dfs = {'aggr_combine_trk': aggr_combine_trk_df, 'all_aggr_games_trk_df': all_aggr_games_trk_df, 
             'player_crr': player_crr_df, 'player': player_df, 'combine_res': combine_res_df}

scaler = StandardScaler()
aggr_combine_trk_df.head()

,nfl_id,max_speed,avg_speed,max_acceleration,avg_acceleration,min_acceleration,total_frames,drill_type_FORTY_YARD_DASH,drill_type_SHORT_SHUTTLE,drill_type_SKILL_DRILLS_DB,drill_type_SKILL_DRILLS_DL,drill_type_SKILL_DRILLS_LB,drill_type_SKILL_DRILLS_OL,drill_type_SKILL_DRILLS_TE,drill_type_SKILL_DRILLS_WR,drill_type_THREE_CONE_DRILL
0,55867,10.416667,7.966603,5.859557,1.921288,0.076739,52,1,0,0,0,0,0,0,0,0
1,55867,8.630000,4.453024,8.137175,2.873069,0.014907,797,0,0,0,0,1,0,0,0,0
2,55870,8.213333,3.117726,6.552510,2.920588,0.096148,557,0,0,0,0,0,1,0,0,0
3,55874,10.073333,7.554877,5.126226,1.827326,0.161383,54,1,0,0,0,0,0,0,0,0
4,55874,7.876667,2.914891,6.696734,2.675264,0.080069,597,0,0,0,0,0,1,0,0,0

In [21]:
columns_to_transform = aggr_combine_trk_df.columns.difference(['nfl_id'])
aggr_combine_trk_df[columns_to_transform] = scaler.fit_transform(
    aggr_combine_trk_df[columns_to_transform]
)

In [22]:
columns_to_transform = all_aggr_games_trk_df.columns.difference(['nfl_id'])
all_aggr_games_trk_df[columns_to_transform] = scaler.fit_transform(
    all_aggr_games_trk_df[columns_to_transform]
)

In [23]:
all_aggr_games_trk_df = all_aggr_games_trk_df.drop(columns = 'index')

In [24]:
player_crr_df.head()
#separate by position

,nfl_id,career_offensive_snaps,career_defensive_snaps,career_special_teams_snaps,career_games_active,career_games_started,ap_all_pro_1st_team,ap_all_pro_2nd_team,pro_bowl_original_ballot
0,55867,0,1884,92,51,44,1,0,1
1,55870,2802,0,169,47,43,0,0,0
2,55874,3222,0,167,51,49,0,1,0
3,55875,3011,0,170,51,48,0,0,0
4,55877,0,1056,387,51,2,0,0,0